[package]
name = "priority-queue"
version = "0.1.0"
authors = ["karen shea <karen.shea@daimler.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
